/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethodTest1 */

#ifndef _Included_NativeMethodTest1
#define _Included_NativeMethodTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethodTest1
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_NativeMethodTest1_gcd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeMethodTest1
 * Method:    reverseOf
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeMethodTest1_reverseOf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NativeMethodTest1
 * Method:    squareAll
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_NativeMethodTest1_squareAll
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
