/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TaxPayerBridge */

#ifndef _Included_TaxPayerBridge
#define _Included_TaxPayerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TaxPayerBridge
 * Method:    getIncomeTax
 * Signature: (S)D
 */
JNIEXPORT jdouble JNICALL Java_TaxPayerBridge_getIncomeTax
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
